from enum import Enum, auto


class SymbolState(Enum):
    IDLE = "IDLE"
    PREPARING = "PREPARING"
    PLACING_GRID = "PLACING_GRID"
    GRID_ACTIVE = "GRID_ACTIVE"
    POSITIONS_ACTIVE = "POSITIONS_ACTIVE"
    TARGET_PENDING = "TARGET_PENDING"
    TARGET_ACTIVE = "TARGET_ACTIVE"
    LOCKED_EXPOSURE = "LOCKED_EXPOSURE"
    CLOSING = "CLOSING"
    RESETTING = "RESETTING"
    ERROR = "ERROR"
    STOPPED = "STOPPED"


class ExitReason(Enum):
    TARGET_HIT = "TARGET_HIT"
    ALL_GRIDS_FILLED = "ALL_GRIDS_FILLED"
    MANUAL_CLOSE_DETECTED = "MANUAL_CLOSE_DETECTED"
    STARTUP_RECOVERY_CLOSE = "STARTUP_RECOVERY_CLOSE"
    ORDER_PLACEMENT_FAILED = "ORDER_PLACEMENT_FAILED"
    APPLICATION_SHUTDOWN = "APPLICATION_SHUTDOWN"
    UNKNOWN_CLOSE_REASON = "UNKNOWN_CLOSE_REASON"


class EventType(Enum):
    CYCLE_START = "CYCLE_START"
    CYCLE_END = "CYCLE_END"
    GRID_PLACED = "GRID_PLACED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_CLOSED = "POSITION_CLOSED"
    TARGET_SET = "TARGET_SET"
    TARGET_HIT = "TARGET_HIT"
    TARGET_REMOVED = "TARGET_REMOVED"
    ERROR = "ERROR"
    STATE_CHANGE = "STATE_CHANGE"
    RECOVERY = "RECOVERY"
    SHUTDOWN = "SHUTDOWN"
    INFO = "INFO"


class OrderStatus(Enum):
    REQUESTED = "REQUESTED"
    PLACED = "PLACED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"


class CycleStatus(Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    CLOSING = "CLOSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ShutdownMode(Enum):
    LEAVE_OPEN = "leave_open"
    CANCEL_PENDING_ONLY = "cancel_pending_only"
    CLOSE_CURRENT_CYCLES = "close_current_cycles"


class ConsoleMode(Enum):
    RICH = "rich"
    PLAIN = "plain"
